run:
  timeout: 2m

linters:
  enable-all: true
  disable:
    # deprecations
    - gomnd # deprecated (since v1.58.0) in favor of 'mnd'
    - execinquery # deprecated (since v1.58.0) as it has been archived
    # other
    - depguard # not used (by default reports many false positives)
    - wsl # we don't want that many whitespaces and white lines


linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/bountysecurity/gbounty)

    # Skip generated files.
    skip-generated: false

    # Make the section order the same as the order of `sections`.
    custom-order: true

issues:
  max-issues-per-linter: 1000
  max-same-issues: 1000