run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    # deprecations:
    - gomnd # (since v1.58.0) in favor of 'mnd'
    - execinquery # (since v1.58.0) as it has been archived
    # we don't want that many whitespaces and white lines
    - wsl
    - nlreturn
    # annoying linters that report many false positives
    - depguard
    - wrapcheck
    # other
    - varnamelen # we want freedom for choosing variable names
    - lll # we try (not force) to keep the lines at a reasonable length
    - exhaustruct # why? isn't it against Go idiomatic zero-value behave?


linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/bountysecurity/gbounty)

    # Skip generated files.
    skip-generated: false

    # Make the section order the same as the order of `sections`.
    custom-order: true

issues:
  max-issues-per-linter: 1000
  max-same-issues: 1000