run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    # deprecations:
    - gomnd # (since v1.58.0) in favor of 'mnd'
    - execinquery # (since v1.58.0) as it has been archived
    # we don't want that many whitespaces and white lines
    - wsl
    - nlreturn
    # annoying linters that report many false positives
    - depguard
    - wrapcheck
    - nilnil
    - gochecknoinits
    - nakedret
    # other
    - varnamelen # we want freedom for choosing variable names
    - tagliatelle # we want freedom for choosing json mapping depending on requirements (external services, etc)
    - lll # we try (not force) to keep the lines at a reasonable length
    - exhaustruct # why? isn't it against Go idiomatic zero-value behave?
    - nonamedreturns # we are fine with named returns so far
    - musttag # sometimes we are just fine with defaults
    - containedctx # for now, we are fine with context being passed around
    - stylecheck # it is annoying, and sometimes ugly to have to write certain things capitalized
    # perhaps revisit?
    - cyclop
    - funlen
    - gocognit
    # enable when on Go v1.22
    - copyloopvar
    - intrange

linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/bountysecurity/gbounty)

    # Skip generated files.
    skip-generated: false

    # Make the section order the same as the order of `sections`.
    custom-order: true

issues:
  max-issues-per-linter: 1000
  max-same-issues: 1000

  exclude-rules:
    # It's fine to disable some of the linters
    # for test files.
    - path: .*_test\.go
      linters:
        - dupl # false positives
        - perfsprint # performance doesn't matter in tests
    - path: internal/profile/profilefakes/.*\.go
      linters:
        - dupl
    - path: internal/profile/request.go
      linters:
        - dupl
    - path: internal/profile/response.go
      linters:
        - dupl
    - path: internal/platform/http/client/reader.go
      linters:
        - mnd
    - path: kit/osext/.*\.go
      linters:
        - mnd
    - path: internal/platform/filesystem/.*\.go
      linters:
        - dupl
        - mnd
    - path: internal/platform/writer/.*\.go
      linters:
        - dupl
        - nestif
        - mnd
    - path: kit/slices/slices.go
      linters:
        - ireturn
    - path: cmd/gbounty/bootstrap/bootstrap.go
      linters:
        - nestif